[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[[headers]]
  for = "/.well-known/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Content-Type = "application/json"

[[headers]]
  for = "/openapi.json"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Content-Type = "application/json"

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"

[[redirects]]
  from = "/api/plot"
  to = "/.netlify/functions/plot"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
